name: systego
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  awesome_snackbar_content: ^0.1.8
  cached_network_image: ^3.4.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.3.1
  dio: ^5.9.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  simple_barcode_scanner: ^0.3.0
  socket_io_client: ^3.1.2
  flutter_blue_plus: ^1.32.11
  screenshot: ^3.0.0
  easy_localization: ^3.0.8
  esc_pos_utils_plus: ^2.0.3  # التغيير الأساسي
  image: ^4.0.0 
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Rubik/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/systego_logo.jpeg"